### ISSUE TITLE
Meta key is not storing in database.

### ISSUE THREAD

**Issue by jainnidhi** [tomimaen/zilla-likes#2]
Hello,

I've created a custom layout for custom post type and used zilla likes shortcode.

Now I want to update like values in database manually.

I've tried to find meta key `_zilla_likes` in the database but couldn't find it.

Am I doing something wrong?

Can you please help me out?

Thanks in advance!

**Comment by tomimaen** [comment]
Hi!

Sorry for the late reply, I was on vacation. ☀️

Did you solve this problem already or do you still need help with it?

**Comment by jainnidhi** [comment]
Still, I need help. I couldn't find the solution for this.

**Comment by tomimaen** [comment]
Is the zilla-likes.js file loaded correctly and does the number increase from zero to one when you click the like button on the shortcode? Do you see any error on the browser's console?

**Comment by jainnidhi** [comment]
No, I can't see any error in the console and like's numbers increasing perfectly but I couldn't find this likes number in the database.
Is there any specific table in which I should find?

**Comment by tomimaen** [comment]
Ah gotcha. You can find the meta key for the single post on wp_postmeta table. Look for the meta field by filtering the wp_postmeta rows by searching with the post id.
